/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * Detail.java
 *
 * Created on Nov 30, 2021, 9:54:11 AM
 */
package View.subUI.FormDetail;

import java.awt.event.MouseEvent;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author Administrator
 */
public class FormShow extends javax.swing.JFrame {

    /**
     * Creates new form Detail
     *
     */
    public FormShow() {
        initComponents();
    }

    public void showDetail(TabDetail tabDetail) {
        java.awt.EventQueue.invokeLater(() -> {
            add(tabDetail);
            setTitle(tabDetail.getBoss().getName());
            setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        setSize(new java.awt.Dimension(407, 327));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
}//GEN-LAST:event_formKeyTyped
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
