/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * PanelDetail.java
 *
 * Created on Jan 24, 2022, 5:18:06 PM
 */
package View.subUI.FormDetail;

import View.subUI.AbsUI;
import View.subUI.SubUI.AbsSubUi;
import java.util.HashMap;

/**
 *
 * @author Administrator
 */
public class TabDetail extends AbsUI {

    private final HashMap<String, AbsSubUi> tabElemnt;
    private final AbsSubUi boss;

    /**
     * Creates new form PanelDetail
     *
     * @param boss
     */
    public TabDetail(AbsSubUi boss) {
        super(boss.getName());
        this.tabElemnt = new HashMap<>();
        initComponents();
        this.boss = boss;
    }

    public AbsSubUi getBoss() {
        return this.boss;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabDetail = new javax.swing.JTabbedPane();

        setLayout(new java.awt.BorderLayout());

        tabDetail.setFont(new java.awt.Font("Tahoma", 1, 14));
        tabDetail.setName("tabDetail"); // NOI18N
        tabDetail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tabDetailKeyTyped(evt);
            }
        });
        add(tabDetail, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void tabDetailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabDetailKeyTyped
// TODO add your handling code here:
}//GEN-LAST:event_tabDetailKeyTyped
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabDetail;
    // End of variables declaration//GEN-END:variables

    public void clear() {
        this.tabDetail.removeAll();
    }

    public void addTab(AbsTabUI tabUI) {
        this.tabDetail.addTab(tabUI.getName(), tabUI);
    }

}
