/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelTabView.java
 *
 * Created on Feb 7, 2022, 9:57:51 AM
 */
package View.subUI.FormDetail;

import java.awt.event.KeyEvent;

/**
 *
 * @author Administrator
 */
public class TabView extends AbsTabUI{

    /** Creates new form PanelTabView
     * @param name */
    public TabView(String name) {
        super(name);
        initComponents();
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbStatus = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        lbStatus.setBackground(new java.awt.Color(102, 102, 255));
        lbStatus.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbStatus.setText("READY");
        lbStatus.setName("lbStatus"); // NOI18N
        lbStatus.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbStatus;
    // End of variables declaration//GEN-END:variables


    @Override
    public void keyEvent(KeyEvent evt) {
    }

    @Override
    public void updateData() {
    }
}
