/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * TagLog.java
 *
 * Created on Feb 7, 2022, 6:28:13 PM
 */
package View.subUI.FormDetail.TabItem;

import Model.DataSource.ModeTest.FunctionConfig.FunctionName;
import Model.DataTest.FunctionData.FunctionData;
import Model.ErrorLog;
import View.subUI.FormDetail.AbsTabUI;
import View.subUI.FormDetail.TabItem.ShowLog.ShowLog;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class TabItem extends AbsTabUI {

    private static final String STATUS_COULMN = "Status";
    private static final String TIME_COULMN = "Time";
    private static final String ITEM_COULMN = "Item";
    private static final String STT_COULMN = "STT";
    private static final String ERROR_CODE_COULMN = "Error code";
    private static final String CUS_ERROR_CODE_COULMN = "Cus error code";
    private final Vector<String> testColumn;
    private final Vector<String> listFunc;
    private final Map<FunctionData, ShowLog> itemLogs;
    private DefaultTableModel tableModel;
    private final List<Boolean> itemFinish;

    /**
     * Creates new form TagLog
     *
     * @param type
     */
    public TabItem(String type) {
        super("Item", type, 1000);
        initComponents();
        this.itemFinish = new ArrayList<>();
        this.testColumn = new Vector<>();
        this.listFunc = new Vector<>();
        this.itemLogs = new HashMap<>();
        addTestClomn();
        addListClomn();
        initTable(this.testColumn);
    }

    private void addListClomn() {
        this.listFunc.add(STT_COULMN);
        this.listFunc.add(ITEM_COULMN);
    }

    private void addTestClomn() {
        this.testColumn.add(STT_COULMN);
        this.testColumn.add(ITEM_COULMN);
        this.testColumn.add(TIME_COULMN);
        this.testColumn.add(STATUS_COULMN);
        this.testColumn.add(CUS_ERROR_CODE_COULMN);
        this.testColumn.add(ERROR_CODE_COULMN);
    }

    private void initTable(Vector<String> column) {
        int maxWith = (int) ((this.getWidth() - 1) / 6);
        int minWith = (int) (maxWith / 3);
        int[] sizeColumn = {minWith, maxWith, minWith, minWith, maxWith, maxWith};
        this.itemFinish.clear();
        this.tableItem.setModel(
                new javax.swing.table.DefaultTableModel(null, column) {
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        });
        this.tableItem.getTableHeader().setReorderingAllowed(true);//
        this.tableItem.setShowGrid(true);
        this.tableModel = (DefaultTableModel) this.tableItem.getModel();
        for (int i = 0; i < column.size(); i++) {
            setPropertiesColumn(i, sizeColumn[i], JLabel.CENTER, JLabel.CENTER);
        }
    }

    private void setPropertiesColumn(int index, int width, int alignment, int header) {
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(alignment);
        this.tableItem.getColumnModel().getColumn(index).setMinWidth(width);
        this.tableItem.getColumnModel().getColumn(index).setCellRenderer(renderer);
        this.tableItem.getColumnModel().getColumn(index).setResizable(false);
        DefaultTableCellRenderer renderer1 = new DefaultTableCellRenderer();
        renderer1.setHorizontalTextPosition(header);
        this.tableItem.getColumnModel().getColumn(index).setHeaderRenderer(renderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableItem = new javax.swing.JTable();

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tableItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tableItem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tableItem.setModel(new javax.swing.table.DefaultTableModel(
            null,
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableItem.setName("tableItem"); // NOI18N
        tableItem.setRowHeight(30);
        tableItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableItemMouseClicked(evt);
            }
        });
        tableItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                keyEvent(evt);
            }
        });
        jScrollPane1.setViewportView(tableItem);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableItemMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() > 1) {
            showItemLogSelected();
        }
    }//GEN-LAST:event_tableItemMouseClicked

    private void showItemLogSelected() {
        FunctionName functionName = getNameITem(this.tableItem.getSelectedRow());
        FunctionData dataBox = this.uiStatus.getProcessData().getDataBox(functionName);
        if (dataBox == null) {
            return;
        }
        if (itemLogs.containsKey(dataBox)) {
            itemLogs.get(dataBox).showLog();
        } else {
            ShowLog itemLog = new ShowLog(this);
            itemLog.setDataBox(dataBox, uiStatus);
            itemLog.showLog();
            itemLogs.put(dataBox, itemLog);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableItem;
    // End of variables declaration//GEN-END:variables

    private void showListFunction() {
        initTable(listFunc);
        for (FunctionName funcName : this.uiStatus.getModeTest().getModeTestSource().getItemTestFunctions()) {
            this.tableModel.addRow(new Object[]{this.tableModel.getRowCount(), funcName});
        }
    }

    @Override
    public void keyEvent(KeyEvent evt) {
        if (!isVisible()) {
            return;
        }
        if (!this.uiStatus.isTesting()) {
            if (evt.getKeyChar() == CTRL_S) {
                showListFunction();
            } else if (evt.getKeyChar() == CTRL_D
                    && this.uiStatus.getModeTest().canDebug()
                    && this.tableItem.getSelectedRowCount() > 0) {
                this.uiStatus.getCellTest().testDebugItem(getListSelectedItem());
            }
        } else if (evt.getKeyChar() == CTRL_Q && isAccepToStopTest()) {
            this.uiStatus.getCellTest().stopTest();
        }
    }
    private static final int CTRL_S = 19;
    private static final int CTRL_D = 4;
    private static final int CTRL_Q = 17;

    @Override
    public void startTest() {
        for (ShowLog itemLog : itemLogs.values()) {
            itemLog.dispose();
        }
        itemLogs.clear();
        initTable(testColumn);
        super.startTest();
    }

    @Override
    public void endTest() {
        updateData();
        super.endTest(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public void updateData() {
        if (!this.isVisible()) {
            return;
        }
        updateListItemTest();
    }

    private void editRow(Object value, int row, String colmn) {
        if (row < 0 || !this.testColumn.contains(colmn)) {
            return;
        }
        this.tableModel.setValueAt(value, row, this.testColumn.indexOf(colmn));
    }

    private String getStatus(FunctionData functionData) {
        if (functionData.isTesting()) {
            return "Testing";
        } else if (functionData.isWaiting()) {
            return "Waiting";
        }
        return functionData.getStatusTest();
    }

    private FunctionName getNameITem(int row) {
        if (row == -1 || row >= this.tableModel.getRowCount()) {
            return null;
        }
        return (FunctionName) this.tableModel.getValueAt(row, this.listFunc.indexOf(ITEM_COULMN));
    }

    private synchronized void updateListItemTest() {
        if (!this.isVisible()) {
            return;
        }
        try {
            FunctionData dataBox;
            List<FunctionData> dataBoxs = this.uiStatus.getProcessData().getDataBoxs();
            for (int row = 0; row < dataBoxs.size(); row++) {
                if (isHasFinish(row)) {
                    continue;
                }
                dataBox = dataBoxs.get(row);
                if (row > this.tableModel.getRowCount() - 1) {
                    this.tableModel.addRow(new Object[]{this.tableModel.getRowCount()});
                    this.itemFinish.add(false);
                    showDataTest(dataBox, row);
                } else {
                    showDataTest(dataBox, row);
                }
                if (dataBox.isDone() ) {
                    this.itemFinish.set(row, true);
                }
            }
        } catch (Exception e) {
            ErrorLog.addError(this, e.getLocalizedMessage());
        }
    }

    private void showDataTest(FunctionData dataBox, int row) {
        editRow(dataBox.getFunctionName(), row, ITEM_COULMN);
        editRow(String.format("%.3f S", dataBox.getRunTime()),
                row, TIME_COULMN);
        editRow(getStatus(dataBox), row, STATUS_COULMN);
        editRow(dataBox.getLocalErrorCode(), row, ERROR_CODE_COULMN);
        editRow(dataBox.getLimitsErrorCode(), row, CUS_ERROR_CODE_COULMN);
    }

    private boolean isHasFinish(int row) {
        return row < this.itemFinish.size() && this.itemFinish.get(row);
    }

    private List<FunctionName> getListSelectedItem() {
        List<FunctionName> result = new ArrayList<>();
        for (int selectedRow : this.tableItem.getSelectedRows()) {
            result.add(getNameITem(selectedRow));
        }
        return result;
    }

    private boolean isAccepToStopTest() {
        return JOptionPane.showConfirmDialog(null,
                "Chọn \"Yes\" để dừng test", "Messager",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION;
    }

    public void removeShowLog(FunctionData key) {
        this.itemLogs.remove(key);
    }
}
