/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * NewJPanel.java
 *
 * Created on May 11, 2022, 9:27:49 AM
 */
package View.subUI.FormDetail.TabFaApi;

import com.alibaba.fastjson.JSONObject;
import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Administrator
 */
public class TabOption extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private final String name;
    private boolean hasChange;

    public TabOption(String name) {
        initComponents();
        AutoCompleteDecorator.decorate(cbbResonCode);
        this.hasChange = true;
        this.name = name;
    }

    public JSONObject getData() {
        if (isInputEmpty()) {
            return null;
        }
        JSONObject result = new JSONObject();
        result.put(TabFaApi.ACTION, getAction());
        result.put(TabFaApi.LOCATION, name);
        result.put(TabFaApi.REASON_DES, getReasonDes());
        result.put(TabFaApi.REPAIR_DETAIL, getRepairDetail());
        result.put(TabFaApi.RESON_CODE, getResonCode());
        config();
        return result;
    }
    

    public String getAction() {
        return this.cbbRepairAction.getSelectedItem().toString();
    }

    public String getReasonDes() {
        return this.cbbReasonDescription.getSelectedItem().toString();
    }

    public String getRepairDetail() {
        return this.cbbRepairDetails.getSelectedItem().toString();
    }
    
    public String getResonCode() {
        return this.cbbResonCode.getSelectedItem().toString();
    }

    @Override
    public String getName() {
        return this.name;
    }

    public boolean hasChange() {
        return hasChange;
    }

    public boolean isInputEmpty() {
        return this.cbbReasonDescription.getSelectedItem().toString().isEmpty()
                || this.cbbRepairAction.getSelectedItem().toString().isEmpty()
                || this.cbbResonCode.getSelectedItem().toString().isEmpty()
                || this.cbbRepairDetails.getSelectedItem().toString().isEmpty();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbbRepairAction = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbbRepairDetails = new javax.swing.JComboBox();
        cbbReasonDescription = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cbbResonCode = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();

        cbbRepairAction.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cbbRepairAction.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "","replace", "reflow", "clean", "scrap" }));
        cbbRepairAction.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbRepairActionItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Repair action");

        jLabel5.setFont(new java.awt.Font("Tahoma 14", 1, 14)); // NOI18N
        jLabel5.setText("Repair details");

        cbbRepairDetails.setFont(new java.awt.Font("Tahoma 18", 1, 18)); // NOI18N
        cbbRepairDetails.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"", "Further details", "vendor", "D/C", "L/c" }));
        cbbRepairDetails.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbRepairDetailsItemStateChanged(evt);
            }
        });

        cbbReasonDescription.setFont(new java.awt.Font("Tahoma 18 12", 1, 18)); // NOI18N
        cbbReasonDescription.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "","SOLDER SHORT", "OTHER" }));
        cbbReasonDescription.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbReasonDescriptionItemStateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma 14 14", 1, 14)); // NOI18N
        jLabel6.setText("Reason description");

        cbbResonCode.setFont(new java.awt.Font("Tahoma 18 12", 1, 18)); // NOI18N
        cbbResonCode.setModel(new javax.swing.DefaultComboBoxModel(new Object[]{}));
        cbbResonCode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbResonCodeItemStateChanged(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma 14 14", 1, 14)); // NOI18N
        jLabel7.setText("Reason code");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbRepairDetails, 0, 90, Short.MAX_VALUE)
                    .addComponent(cbbRepairAction, 0, 90, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbResonCode, 0, 93, Short.MAX_VALUE)
                    .addComponent(cbbReasonDescription, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbReasonDescription)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(cbbRepairAction))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbbResonCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(cbbRepairDetails, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                        .addGap(1, 1, 1)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbbRepairActionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbRepairActionItemStateChanged
        checkChang(evt);
    }//GEN-LAST:event_cbbRepairActionItemStateChanged

    private void cbbRepairDetailsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbRepairDetailsItemStateChanged
        // TODO add your handling code here:
        checkChang(evt);
    }//GEN-LAST:event_cbbRepairDetailsItemStateChanged

    private void cbbReasonDescriptionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbReasonDescriptionItemStateChanged
        // TODO add your handling code here:
        checkChang(evt);
    }//GEN-LAST:event_cbbReasonDescriptionItemStateChanged

    private void cbbResonCodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbResonCodeItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbResonCodeItemStateChanged

    private void checkChang(ItemEvent evt) {
        // TODO add your handling code here:
        hasChange = evt.getStateChange() == ItemEvent.SELECTED;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbbReasonDescription;
    private javax.swing.JComboBox cbbRepairAction;
    private javax.swing.JComboBox cbbRepairDetails;
    private javax.swing.JComboBox cbbResonCode;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

    void config() {
        hasChange = false;
    }

    void setListResonCode(String[] listResonCode) {
        this.cbbResonCode.setModel(new DefaultComboBoxModel(listResonCode));
    }

}
